### PR TITLE
fix(wrapper): include wrapper handler in package

### PR DESCRIPTION
**Pull request by juanjoDiaz**
This solves a problem reported at https://github.com/FidelLimited/serverless-plugin-warmup/pull/134

Essentially this plugin doesn't work with functions packaged individually or functions that exclude most files in the solution.

Not thoroughly tested since I'm not using epsagon at the moment and there are not tests.

### CODE REVIEW

**Comment by ranrib** [comment]
Hi @juanjoDiaz can you give an example that doesn't work in the current version of the plugin? I couldn't reproduce what you're saying

**Comment by juanjoDiaz** [comment]
The problem is visible when using the package setting.

For example, if I set my function like:
```yaml
package:
  exclude:
    - **
  include:
    - src/function/handler.js
```
since everything is excluded from the bundle (the zip file that's sent to AWS) except the handler, the epsagon handler is not included in the package and not found at runtime.

This PR, explicitly include the epsagon package in the bundle so it can be found at runtime.

**Comment by ranrib** [comment]
Perfect - I've also added a case where there is global package exclusion (and not per function).

**Comment by juanjoDiaz** [comment]
That shouldn't be needed since the per-function config takes precedence over the package config.

**Comment by ranrib** [comment]
I thought so, but it's not true. The following conf doesn't work:
```
service: test-python

package:
  exclude:
    - ./**
  include:
    - handler.py

plugins:
  - serverless-plugin-epsagon

custom:
  epsagon:
    token: your-token-here
    appName: optional-application-name

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    package:
      exclude:
        - ./**
      include:
        - handler.py
```

**Comment by juanjoDiaz** [comment]
What version of serverless are you using?
I implemented that feature myself on https://github.com/serverless/serverless/pull/5364

**Pull request merged**
